#!/usr/bin/env bash

cp /etc/hosts /etc/hosts.bak

sudo sed -i "/localhost/d" /etc/hosts
echo "127.0.0.2\tlocalhost" >> /etc/hosts
sudo sed -i "/facebook.com/d" /etc/hosts
echo "8.8.8.8\tfacebook.com" >> /etc/hosts
