#!/usr/bin/env bash
#fizzbuzz bash script

i=1
while [ ! $i -eq 101 ];
do
	if [ $(($i % 3)) -eq 0 ] && [ $(($i % 5)) -eq 0 ]; then
		printf "FizzBuzz\n"
	elif [ $(($i % 3)) -eq 0 ]; then
		printf "Fizz\n"
	elif [ $(($i % 5)) -eq 0 ]; then
		printf "Buzz\n"
	else
		printf "$i\n"
	fi
	((i++))
done
