#!/usr/bin/env bash
#prints best school until last iteration then hi

i=0
while [ $i -lt 9 ];
do
	if [ $i == 8 ]; then
		printf "Best School\n"
		printf "Hi\n"
	fi
		printf "Best School\n"
	((i++))
done
