#!/usr/bin/env bash
#prints best school until last iteration then hi

i=0
while [ $i -lt 10 ];
do
	if [ $i == 9 ]; then
		printf("Best School\n")
		printf("Hi")
	fi
		printf("Best School\n")
	((i++))
done
