#!/usr/bin/env bash
#prints text that differsbase on iteration num

i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 3 ]; then
		printf "bad luck\n"
	elif [ $i -eq 7 ]; then
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
	((i++))
done
