#!/usr/bin/env bash
#prints text that differsbase on iteration num

i=1
while [ $i -lt 11 ];
do
	if [ $i -eq 4 ]; then
		printf "bad luck\n"
	elif [ $i -eq 8 ]
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
done
printf "Best School"
