#!/usr/bin/env bash
#prints number 1 - 20 or special condition prints

i=1
while [$i -lt 21];
do
	if [ ! $i == 5] && [ ! $i == 10 ] && [ ! $i == 18 ]; then
		echo "$i"
	case [ $i -eq 5 ]
		printf("bad luck from China\n")
	case [ $i -eq == 10 ]
		printf("bad luck from Japan\n")
	case [ $i -eq == 18 ]
		printf("bad luck from Italy\n")
done
