#!/usr/bin/env bash
#prints number 1 - 20 or special condition prints

i=1
while [ $i -lt 21 ];
do
	case $i in
		20)
			printf "$i"
			break
			;;
		4)
			printf "4\nbad luck from China\n"
			;;
		9)
			printf "8\nbad luck from Japan\n"
			;;
		17)
			printf "17\nbad luck from Italy\n"
			;;
		*)
			printf "$i\n"
	esac
	((i++))
done
