#!/usr/bin/env bash
#if a file exists print some output

if [ -e "school" ]; then
	printf "school file exists\n"
	if [ ! $(stat -c "%d" "school") -eq 0 ]; then
		printf "school file is not empty\n"
	else
		printf "school file is empty\n"
	fi
	if [ -f "school" ]; then
		printf "school is a regular file\n"
	fi
else
	printf "school file does not exist\n"
fi
